package gestion.torneos.ui;

import gestion.torneos.controller.GestorNuevoAspirante;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 * Clase que representa la pantalla de creación de aspirantes.
 *
 * @author Leandro Giménez
 * @version 1.0
 */
public class PantallaNuevoAspirante extends javax.swing.JDialog {

    private static final Logger _logger = Logger.getLogger(PantallaNuevoAspirante.class);

    private GestorNuevoAspirante gestorNuevoAspirante = null;

    /**
     * Constructor que recibe una instancia del gestor de nuevo aspirante.
     *
     * @param gestorNuevoAspirante Gestor de Nuevo Aspirante.
     */
    public PantallaNuevoAspirante(GestorNuevoAspirante gestorNuevoAspirante) {
        super(new JFrame(), true);
        _logger.debug("Iniciando GUI nuevo aspirante");
        this.gestorNuevoAspirante = gestorNuevoAspirante;
        initComponents();
        this.setLocationRelativeTo(null); 
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoButtonGroup = new javax.swing.ButtonGroup();
        nombresLabel = new javax.swing.JLabel();
        nombresTextField = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        apellidoTextField = new javax.swing.JTextField();
        direccionLabel = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        fechaNacimientoLabel = new javax.swing.JLabel();
        fechaNacimientoTextField = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        masculinoRadioButton = new javax.swing.JRadioButton();
        femeninoRadioButton = new javax.swing.JRadioButton();
        dniLabel = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        dniTextField = new javax.swing.JTextField();

        sexoButtonGroup.add(masculinoRadioButton);
        sexoButtonGroup.add(femeninoRadioButton);
        masculinoRadioButton.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Aspirante");
        setIconImage(Toolkit.getDefaultToolkit().getImage(
            getClass().getResource(
                "/resources/img/athletics-16x16.png")));

    nombresLabel.setText("Nombres: ");

    nombresTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nombresTextFieldActionPerformed(evt);
        }
    });

    apellidoLabel.setText("Apellido:  ");

    direccionLabel.setText("Dirección:");

    fechaNacimientoLabel.setText("Fecha de Nacimiento: ");

    TextPrompt placeholder = new TextPrompt("Formato dd/mm/aaaaa", fechaNacimientoTextField);
    placeholder.changeAlpha(0.75f);
    placeholder.changeStyle(Font.ITALIC);

    sexoLabel.setText("Sexo: ");

    masculinoRadioButton.setText("Masculino");

    femeninoRadioButton.setText("Femenino");

    dniLabel.setText("DNI: ");

    aceptarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/accept-16x16.png"))); // NOI18N
    aceptarButton.setText("Aceptar");
    aceptarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            aceptarButtonActionPerformed(evt);
        }
    });

    cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/cancel-16x16.png"))); // NOI18N
    cancelarButton.setText("Cancelar");
    cancelarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelarButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dniLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(direccionLabel)
                        .addComponent(fechaNacimientoLabel)
                        .addComponent(apellidoLabel)
                        .addComponent(nombresLabel)
                        .addComponent(sexoLabel))
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaNacimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(masculinoRadioButton)
                                .addComponent(aceptarButton))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cancelarButton)
                                .addComponent(femeninoRadioButton))))
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aceptarButton, cancelarButton});

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {apellidoTextField, direccionTextField, dniTextField, fechaNacimientoTextField, nombresTextField});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nombresLabel)
                .addComponent(nombresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(apellidoLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(direccionLabel)
                .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fechaNacimientoLabel)
                .addComponent(fechaNacimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dniLabel)
                .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sexoLabel)
                .addComponent(masculinoRadioButton)
                .addComponent(femeninoRadioButton))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(aceptarButton)
                .addComponent(cancelarButton))
            .addContainerGap(16, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresTextFieldActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        try {
            String nombres = nombresTextField.getText();
            String apellido = apellidoTextField.getText();
            String direccion = direccionTextField.getText();
            String fechaNacimiento = fechaNacimientoTextField.getText();
            String dni = dniTextField.getText();
            String sexo = masculinoRadioButton.isSelected() ? "MASCULINO" : "FEMENINO";

            ResultadoValidacionNuevoAspirante resultadoValidacion = this.gestorNuevoAspirante.validarDatosNuevoAspirante(nombres, apellido, fechaNacimiento, dni);
            // Si hay errores de validación...
            if (!resultadoValidacion.isNuevoAspiranteOk()) {
                StringBuilder errorBuffer = new StringBuilder();
                errorBuffer.append("Verifique los siguientes campos: \n");
                if (!resultadoValidacion.isNombreOk()) {
                    errorBuffer.append("El nombre es obligatorio\n");
                }
                if (!resultadoValidacion.isApellidoOk()) {
                    errorBuffer.append("El apellido es obligatorio\n");
                }
                if (!resultadoValidacion.isFechaNacimientoOk()) {
                    errorBuffer.append("La fecha de nacimiento es obligatoria\n");
                } else if (!resultadoValidacion.isFechaNacimientoFormatoOk()) {
                    errorBuffer.append("Formato de fecha inválido\n");
                } else if (!resultadoValidacion.isFechaIngresadaMenorQueActualOk()) {
                    errorBuffer.append("La fecha ingresada debe ser menor a la fecha actual\n");
                } else if (!resultadoValidacion.isRangoDeEdadOk()) {
                    errorBuffer.append("Verifique fecha de nacimiento, ");
                    errorBuffer.append("rango de edad inválido. Rango de edad válido = ");
                    errorBuffer.append("[").append(GestorNuevoAspirante.EDAD_MINIMA_ASPIRANTE).append(",");
                    errorBuffer.append(GestorNuevoAspirante.EDAD_MAXIMA_ASPIRANTE).append("]");
                    errorBuffer.append("\n");
                }
                if (!resultadoValidacion.isDniOk()) {
                    errorBuffer.append("El DNI es obligatorio\n");
                } else if (!resultadoValidacion.isDniSoloNumerosOk()) {
                    errorBuffer.append("DNI solo debe contener números\n");
                } else if (!resultadoValidacion.isDniLongitudOk()) {
                    errorBuffer.append("El DNI debe tener ").append(GestorNuevoAspirante.LONGITUD_MAXIMA_DNI).append(" números\n");
                } else if (!resultadoValidacion.isDniExistenteOk()) {
                    errorBuffer.append("El DNI ingresado ya existe en el sistema\n");
                }

                JOptionPane.showMessageDialog(this, errorBuffer.toString(), "Errores de validación", JOptionPane.ERROR_MESSAGE);
            } else {
                this.gestorNuevoAspirante.crearAspirante(nombres, apellido, fechaNacimiento, dni, sexo, direccion);
            }
        } catch (Exception ex) {
            _logger.error("Error al validar el formulario de nuevo aspirante: " + ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, "Ocurrió un error al validar el formulario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.gestorNuevoAspirante.cancelarOperacion();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JLabel fechaNacimientoLabel;
    private javax.swing.JTextField fechaNacimientoTextField;
    private javax.swing.JRadioButton femeninoRadioButton;
    private javax.swing.JRadioButton masculinoRadioButton;
    private javax.swing.JLabel nombresLabel;
    private javax.swing.JTextField nombresTextField;
    private javax.swing.ButtonGroup sexoButtonGroup;
    private javax.swing.JLabel sexoLabel;
    // End of variables declaration//GEN-END:variables
}
